apiVersion: v1
kind: Service
metadata:
  name: webapp-network-tester-external
  namespace: demos-external
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: webapp-network-tester-external

