apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-network-tester-external
  namespace: demos-external
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-network-tester-external
  template:
    metadata:
      labels:
        app: webapp-network-tester-external
    spec:
      containers:
      - image: jannemattila/webapp-network-tester:latest
        imagePullPolicy: Always
        name: webapp-network-tester-external
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
