apiVersion: v1
kind: Service
metadata:
  name: webapp-network-tester-external-shared
  namespace: demos-external
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "internal-subnet"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: webapp-network-tester-external

