apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-network-tester
  namespace: demos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-network-tester
  template:
    metadata:
      labels:
        app: webapp-network-tester
    spec:
      # nodeSelector:
      #   usage: limitedaccess
      # tolerations:
      # - key: "usage"
      #   operator: "Equal"
      #   value: "limitedaccess"
      #   effect: "NoSchedule"
      containers:
      - image: jannemattila/webapp-network-tester:latest
        imagePullPolicy: Always
        name: webapp-network-tester
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 150m
        #     memory: 150Mi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 5201
          name: iperf3tcp
          protocol: TCP
        - containerPort: 5202
          name: iperf3udp
          protocol: UDP
